[package]
name = "ReView"
version = "0.1.0"
authors = ["TheDome"]
edition = "2018"
build = "build.rs"
repository = "https://github.com/thedome/review"
description = "A simple program to use the remarkable live view feature"
readme = "README.md"

[features]
session_from_config = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zip = "0.5.11"
reqwest = { version = "0.11.0", features = ["default-tls", "json"] }
env_logger = "0.8.2"
websocket = "0.26.2"
json = "0.12.4"
uuid = { version = "0.8.2", features = ["serde", "v4", ] }
glib = "0.10.3"
cairo-rs = { version = "^0", features = ["v1_16"] }
gdk = "0.13.2"

[dependencies.tokio]
version = "1.0.2"
features = ["macros", "rt-multi-thread"]

[dependencies.gtk]
version = "^0"
features = ["v3_24"]

[dependencies.gio]
version = "0.9.1"
features = ["v2_44"]

[dependencies.log]
version = "0.4.13"
features = ["max_level_trace", "release_max_level_warn"]

